version: '3.8'

services:
  web:
    build: /home/ubuntu/Acik-Kaynak-Yazilim/DorduncuHaftaOdevi/my_web_server
    command: python3 nobelApi.py -h 0.0.0.0
    volumes:
      - /home/ubuntu/Acik-Kaynak-Yazilim/DorduncuHaftaOdevi/my_web_server/:/usr/src/app/
    ports:
      - 5001:5000
